import type { HardwareProduct } from './types.js';

// Catalogo de hardware da loja (estilo KaBuM!). Precos em centavos.
// Especificacoes essenciais para a validacao de compatibilidade do Monte seu PC.

export const CATALOG: readonly HardwareProduct[] = [
  // ===================== 1. PROCESSADORES =====================
  {
    id: 'cpu-r5-5600',
    sku: 'CPU-R5-5600',
    category: 'cpu',
    brand: 'AMD',
    name: 'Ryzen 5 5600',
    priceCents: 89990,
    socket: 'AM4',
    cores: 6,
    threads: 12,
    baseClockGhz: 3.5,
    boostClockGhz: 4.4,
    tdpW: 65,
    highlight: 'Melhor custo-benefício',
  },
  {
    id: 'cpu-r7-5700x',
    sku: 'CPU-R7-5700X',
    category: 'cpu',
    brand: 'AMD',
    name: 'Ryzen 7 5700X',
    priceCents: 139990,
    socket: 'AM4',
    cores: 8,
    threads: 16,
    baseClockGhz: 3.4,
    boostClockGhz: 4.6,
    tdpW: 105,
  },
  {
    id: 'cpu-r5-8600g',
    sku: 'CPU-R5-8600G',
    category: 'cpu',
    brand: 'AMD',
    name: 'Ryzen 5 8600G',
    priceCents: 149990,
    socket: 'AM5',
    cores: 6,
    threads: 12,
    baseClockGhz: 4.3,
    boostClockGhz: 5.0,
    tdpW: 65,
    highlight: 'Com vídeo integrado',
  },
  {
    id: 'cpu-r7-7700x',
    sku: 'CPU-R7-7700X',
    category: 'cpu',
    brand: 'AMD',
    name: 'Ryzen 7 7700X',
    priceCents: 229990,
    socket: 'AM5',
    cores: 8,
    threads: 16,
    baseClockGhz: 4.5,
    boostClockGhz: 5.4,
    tdpW: 105,
  },
  {
    id: 'cpu-i5-12400f',
    sku: 'CPU-I5-12400F',
    category: 'cpu',
    brand: 'Intel',
    name: 'Core i5-12400F',
    priceCents: 99990,
    socket: 'LGA1700',
    cores: 6,
    threads: 12,
    baseClockGhz: 2.5,
    boostClockGhz: 4.4,
    tdpW: 65,
  },
  {
    id: 'cpu-i7-13700k',
    sku: 'CPU-I7-13700K',
    category: 'cpu',
    brand: 'Intel',
    name: 'Core i7-13700K',
    priceCents: 289990,
    socket: 'LGA1700',
    cores: 16,
    threads: 24,
    baseClockGhz: 3.4,
    boostClockGhz: 5.4,
    tdpW: 125,
    highlight: 'Top de linha',
  },

  // ===================== 2. PLACAS-MAE =====================
  {
    id: 'mb-a520m-k',
    sku: 'MB-A520M-K',
    category: 'motherboard',
    brand: 'Gigabyte',
    name: 'A520M-K (mATX, DDR4)',
    priceCents: 54990,
    socket: 'AM4',
    memoryType: 'DDR4',
    formFactor: 'mATX',
    m2Slots: 1,
    sataPorts: 4,
  },
  {
    id: 'mb-b550m-pro',
    sku: 'MB-B550M-PRO',
    category: 'motherboard',
    brand: 'MSI',
    name: 'B550M PRO-VDH WiFi (mATX, DDR4)',
    priceCents: 74990,
    socket: 'AM4',
    memoryType: 'DDR4',
    formFactor: 'mATX',
    m2Slots: 2,
    sataPorts: 6,
  },
  {
    id: 'mb-b650m-gw',
    sku: 'MB-B650M-GW',
    category: 'motherboard',
    brand: 'Gigabyte',
    name: 'B650M Gaming WiFi (mATX, DDR5)',
    priceCents: 109990,
    socket: 'AM5',
    memoryType: 'DDR5',
    formFactor: 'mATX',
    m2Slots: 2,
    sataPorts: 4,
    highlight: 'Mais vendida',
  },
  {
    id: 'mb-b650-plus',
    sku: 'MB-B650-PLUS',
    category: 'motherboard',
    brand: 'ASUS',
    name: 'TUF Gaming B650-Plus (ATX, DDR5)',
    priceCents: 149990,
    socket: 'AM5',
    memoryType: 'DDR5',
    formFactor: 'ATX',
    m2Slots: 3,
    sataPorts: 4,
  },
  {
    id: 'mb-b760m-ds3h',
    sku: 'MB-B760M-DS3H',
    category: 'motherboard',
    brand: 'Gigabyte',
    name: 'B760M DS3H (mATX, DDR5)',
    priceCents: 89990,
    socket: 'LGA1700',
    memoryType: 'DDR5',
    formFactor: 'mATX',
    m2Slots: 2,
    sataPorts: 4,
  },
  {
    id: 'mb-h610m-e',
    sku: 'MB-H610M-E',
    category: 'motherboard',
    brand: 'MSI',
    name: 'PRO H610M-E (mATX, DDR4)',
    priceCents: 64990,
    socket: 'LGA1700',
    memoryType: 'DDR4',
    formFactor: 'mATX',
    m2Slots: 1,
    sataPorts: 4,
  },

  // ===================== 3. MEMORIA RAM =====================
  {
    id: 'ram-ddr4-16',
    sku: 'MEM-DDR4-16',
    category: 'memory',
    brand: 'Kingston',
    name: 'Fury Beast 16GB (2x8GB) 3200MHz',
    priceCents: 32990,
    memoryType: 'DDR4',
    capacityGb: 16,
    sticks: 2,
    speedMhz: 3200,
  },
  {
    id: 'ram-ddr4-32',
    sku: 'MEM-DDR4-32',
    category: 'memory',
    brand: 'Corsair',
    name: 'Vengeance 32GB (2x16GB) 3600MHz',
    priceCents: 59990,
    memoryType: 'DDR4',
    capacityGb: 32,
    sticks: 2,
    speedMhz: 3600,
  },
  {
    id: 'ram-ddr5-16',
    sku: 'MEM-DDR5-16',
    category: 'memory',
    brand: 'Kingston',
    name: 'Fury Beast 16GB (2x8GB) 6000MHz',
    priceCents: 45990,
    memoryType: 'DDR5',
    capacityGb: 16,
    sticks: 2,
    speedMhz: 6000,
  },
  {
    id: 'ram-ddr5-32',
    sku: 'MEM-DDR5-32',
    category: 'memory',
    brand: 'Corsair',
    name: 'Vengeance 32GB (2x16GB) 6000MHz',
    priceCents: 84990,
    memoryType: 'DDR5',
    capacityGb: 32,
    sticks: 2,
    speedMhz: 6000,
    highlight: 'Para jogos pesados',
  },
  {
    id: 'ram-ddr5-32-crucial',
    sku: 'MEM-DDR5-32-CRUCIAL',
    category: 'memory',
    brand: 'Crucial',
    name: '32GB (2x16GB) 5600MHz',
    priceCents: 69990,
    memoryType: 'DDR5',
    capacityGb: 32,
    sticks: 2,
    speedMhz: 5600,
  },

  // ===================== 4. PLACAS DE VIDEO =====================
  {
    id: 'gpu-rx7600',
    sku: 'GPU-RX7600',
    category: 'gpu',
    brand: 'AMD',
    name: 'Radeon RX 7600 8GB',
    priceCents: 159990,
    tdpW: 165,
    lengthMm: 268,
    vramGb: 8,
  },
  {
    id: 'gpu-rtx4060',
    sku: 'GPU-RTX4060',
    category: 'gpu',
    brand: 'NVIDIA',
    name: 'GeForce RTX 4060 8GB',
    priceCents: 199990,
    tdpW: 115,
    lengthMm: 240,
    vramGb: 8,
  },
  {
    id: 'gpu-rtx4060ti',
    sku: 'GPU-RTX4060TI',
    category: 'gpu',
    brand: 'NVIDIA',
    name: 'GeForce RTX 4060 Ti 16GB',
    priceCents: 329990,
    tdpW: 165,
    lengthMm: 244,
    vramGb: 16,
    highlight: '16GB de VRAM',
  },
  {
    id: 'gpu-rx7800xt',
    sku: 'GPU-RX7800XT',
    category: 'gpu',
    brand: 'AMD',
    name: 'Radeon RX 7800 XT 16GB',
    priceCents: 399990,
    tdpW: 263,
    lengthMm: 280,
    vramGb: 16,
  },
  {
    id: 'gpu-rtx4070s',
    sku: 'GPU-RTX4070S',
    category: 'gpu',
    brand: 'NVIDIA',
    name: 'GeForce RTX 4070 Super 12GB',
    priceCents: 449990,
    tdpW: 220,
    lengthMm: 267,
    vramGb: 12,
    highlight: 'Top de linha',
  },

  // ===================== 5. ARMAZENAMENTO =====================
  {
    id: 'ssd-wd240',
    sku: 'SSD-WD240',
    category: 'storage',
    brand: 'WD',
    name: 'Green 240GB SATA 2.5"',
    priceCents: 18990,
    interface: 'SATA',
    formFactor: '2.5"',
    capacityGb: 240,
  },
  {
    id: 'ssd-nv2-500',
    sku: 'SSD-NV2-500',
    category: 'storage',
    brand: 'Kingston',
    name: 'NV2 500GB NVMe M.2',
    priceCents: 25990,
    interface: 'NVMe',
    formFactor: 'M.2',
    capacityGb: 500,
  },
  {
    id: 'ssd-nv2-1tb',
    sku: 'SSD-NV2-1TB',
    category: 'storage',
    brand: 'Kingston',
    name: 'NV2 1TB NVMe M.2',
    priceCents: 44990,
    interface: 'NVMe',
    formFactor: 'M.2',
    capacityGb: 1000,
    highlight: 'Mais vendido',
  },
  {
    id: 'ssd-sn580-1tb',
    sku: 'SSD-SN580-1TB',
    category: 'storage',
    brand: 'WD',
    name: 'Blue SN580 1TB NVMe M.2',
    priceCents: 54990,
    interface: 'NVMe',
    formFactor: 'M.2',
    capacityGb: 1000,
  },
  {
    id: 'hdd-barracuda-2tb',
    sku: 'HDD-BARRACUDA-2TB',
    category: 'storage',
    brand: 'Seagate',
    name: 'Barracuda 2TB 3.5"',
    priceCents: 39990,
    interface: 'SATA',
    formFactor: '3.5"',
    capacityGb: 2000,
  },

  // ===================== 6. FONTES =====================
  {
    id: 'psu-cv550',
    sku: 'PSU-CV550',
    category: 'psu',
    brand: 'Corsair',
    name: 'CV550 550W 80 Plus Bronze',
    priceCents: 34990,
    wattage: 550,
    modular: false,
  },
  {
    id: 'psu-rm650x',
    sku: 'PSU-RM650X',
    category: 'psu',
    brand: 'Corsair',
    name: 'RM650x 650W 80 Plus Gold (modular)',
    priceCents: 64990,
    wattage: 650,
    modular: true,
  },
  {
    id: 'psu-rm750e',
    sku: 'PSU-RM750E',
    category: 'psu',
    brand: 'Corsair',
    name: 'RM750e 750W 80 Plus Gold (modular)',
    priceCents: 69990,
    wattage: 750,
    modular: true,
    highlight: 'Mais vendida',
  },
  {
    id: 'psu-rm850e',
    sku: 'PSU-RM850E',
    category: 'psu',
    brand: 'Corsair',
    name: 'RM850e 850W 80 Plus Gold (modular)',
    priceCents: 79990,
    wattage: 850,
    modular: true,
  },

  // ===================== 7a. GABINETES =====================
  {
    id: 'case-mb-q300l',
    sku: 'CASE-Q300L',
    category: 'case',
    brand: 'Cooler Master',
    name: 'MasterBox Q300L (mATX)',
    priceCents: 29990,
    formFactors: ['mATX', 'ITX'],
    maxGpuLengthMm: 360,
  },
  {
    id: 'case-gamer-vidro',
    sku: 'CASE-GAMER-VIDRO',
    category: 'case',
    brand: 'Gamer',
    name: 'Mid Tower com Vidro Temperado',
    priceCents: 39990,
    formFactors: ['ATX', 'mATX', 'ITX'],
    maxGpuLengthMm: 320,
  },
  {
    id: 'case-4000d',
    sku: 'CASE-4000D',
    category: 'case',
    brand: 'Corsair',
    name: '4000D Airflow (ATX)',
    priceCents: 54990,
    formFactors: ['ATX', 'mATX', 'ITX'],
    maxGpuLengthMm: 360,
    highlight: 'Excelente airflow',
  },
  {
    id: 'case-h510',
    sku: 'CASE-H510',
    category: 'case',
    brand: 'NZXT',
    name: 'H510 Flow (ATX)',
    priceCents: 59990,
    formFactors: ['ATX', 'mATX', 'ITX'],
    maxGpuLengthMm: 365,
  },

  // ===================== 7b. REFRIGERACAO =====================
  {
    id: 'cooler-assassin',
    sku: 'COOLER-ASSASSIN',
    category: 'cooler',
    brand: 'Thermalright',
    name: 'Assassin X 120 (air)',
    priceCents: 18990,
    sockets: ['AM4', 'AM5', 'LGA1700'],
    type: 'air',
    tdpW: 150,
  },
  {
    id: 'cooler-h100x',
    sku: 'COOLER-H100X',
    category: 'cooler',
    brand: 'Corsair',
    name: 'H100x 240mm (water cooling)',
    priceCents: 69990,
    sockets: ['AM4', 'AM5', 'LGA1700'],
    type: 'aio',
    tdpW: 250,
  },
] as const;

export function productsByCategory<C extends HardwareProduct['category']>(
  category: C,
): HardwareProduct[] {
  return CATALOG.filter((p) => p.category === category) as HardwareProduct[];
}

export function productById(id: string): HardwareProduct | undefined {
  return CATALOG.find((p) => p.id === id);
}
